//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_DB_Source
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string DBType { get; set; }
        public string DBIP { get; set; }
        public string Port { get; set; }
        public string DBName { get; set; }
        public string Schema { get; set; }
        public string DBUser { get; set; }
        public string DBPwd { get; set; }
        public string Attach { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
    }
}
