//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FT_Folder
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public string FolderType { get; set; }
        public Nullable<int> PFolderID { get; set; }
        public Nullable<int> FolderLev { get; set; }
        public string Remark { get; set; }
        public string FolderSpace { get; set; }
        public string ViewAuthUsers { get; set; }
        public string DownloadAuthUsers { get; set; }
        public string UploadaAuthUsers { get; set; }
        public string CollectUser { get; set; }
        public string FoldUploadUrl { get; set; }
        public string FoldDowmLoadUrl { get; set; }
        public string ShareCode { get; set; }
        public string SharePasd { get; set; }
        public string ShareType { get; set; }
        public Nullable<System.DateTime> ShareDueDate { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
    }
}
