//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FT_File
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> FolderID { get; set; }
        public string FileExtendName { get; set; }
        public string FileSize { get; set; }
        public Nullable<int> FileDownloadCishu { get; set; }
        public string FileMD5 { get; set; }
        public Nullable<int> FileVersin { get; set; }
        public string IsRecycle { get; set; }
        public string FileUrl { get; set; }
        public string ViewAuthUsers { get; set; }
        public string DownloadAuthUsers { get; set; }
        public string CollectUser { get; set; }
        public string ShareCode { get; set; }
        public string SharePasd { get; set; }
        public string ShareType { get; set; }
        public Nullable<System.DateTime> ShareDueDate { get; set; }
        public string ISYL { get; set; }
        public string Remark { get; set; }
        public string UPUser { get; set; }
        public Nullable<System.DateTime> UPDDate { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string YLUrl { get; set; }
        public string YLCode { get; set; }
        public string YLPath { get; set; }
        public string YLCount { get; set; }
        public string TBStatus { get; set; }
        public Nullable<int> TotalTime { get; set; }
        public string zyid { get; set; }
    }
}
