//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FT_File_Share
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public Nullable<int> RefID { get; set; }
        public string RefType { get; set; }
        public string ShareURL { get; set; }
        public string SharePasd { get; set; }
        public Nullable<System.DateTime> ShareDueDate { get; set; }
        public string ShareType { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string AuthType { get; set; }
        public string IsDel { get; set; }
        public string CRUserName { get; set; }
    }
}
