//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JH_Auth_TL
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public string MSGType { get; set; }
        public string MSGTLYID { get; set; }
        public string MSGTLHFID { get; set; }
        public string MSGContent { get; set; }
        public string MSGisHasFiles { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CRUser { get; set; }
        public string CRUserName { get; set; }
        public string MSGISDele { get; set; }
        public string MsgISShow { get; set; }
        public string Remark { get; set; }
        public string Remark1 { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<int> TLID { get; set; }
        public string ReUser { get; set; }
    }
}
