//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JH_Auth_QY
    {
        public int ComId { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string QYCode { get; set; }
        public string QYName { get; set; }
        public string QYProfile { get; set; }
        public string ContactUser { get; set; }
        public string Position { get; set; }
        public string TelPhone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string TYPE { get; set; }
        public string CreateYear { get; set; }
        public string CreateMonth { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string WebSite { get; set; }
        public string WXUrl { get; set; }
        public string corpId { get; set; }
        public string corpSecret { get; set; }
        public string IsUseWX { get; set; }
        public string SystemGGId { get; set; }
        public string MsgAppID { get; set; }
        public string FileServerUrl { get; set; }
        public string Token { get; set; }
        public string EncodingAESKey { get; set; }
        public string DXQZ { get; set; }
        public string LogoID { get; set; }
        public Nullable<decimal> AccountMoney { get; set; }
        public string wxqrcode { get; set; }
        public Nullable<long> QySpace { get; set; }
        public Nullable<int> QyExpendSpace { get; set; }
        public string TempCode { get; set; }
        public string FinanceLXR { get; set; }
        public string FZR { get; set; }
        public string FLXRDH { get; set; }
        public string FZRDH { get; set; }
        public string wxappid { get; set; }
        public string wxappsecret { get; set; }
        public string wxmchid { get; set; }
        public string wxmchidkey { get; set; }
    }
}
