//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JH_Auth_User_Center
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public string UserTO { get; set; }
        public string UserFrom { get; set; }
        public string MsgType { get; set; }
        public string MsgModeID { get; set; }
        public string MsgContent { get; set; }
        public Nullable<int> IsSend { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CRUser { get; set; }
        public string DataId { get; set; }
        public string MsgLink { get; set; }
        public string wxLink { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public Nullable<int> isRead { get; set; }
        public string isCS { get; set; }
    }
}
