//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JH_Auth_QY_WXSC
    {
        public int ComId { get; set; }
        public int ID { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string SCTemp { get; set; }
        public string SCType { get; set; }
        public string SCPicUrl { get; set; }
        public string SCFileUrl { get; set; }
    }
}
