//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JH_Auth_Role
    {
        public Nullable<int> ComId { get; set; }
        public int RoleCode { get; set; }
        public string RoleName { get; set; }
        public string RoleDec { get; set; }
        public int PRoleCode { get; set; }
        public int DisplayOrder { get; set; }
        public int leve { get; set; }
        public string IsUse { get; set; }
        public string isSysRole { get; set; }
        public Nullable<int> WXBQCode { get; set; }
        public string RoleQX { get; set; }
        public string IsHasQX { get; set; }
    }
}
