//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JH_Auth_Branch
    {
        public Nullable<int> ComId { get; set; }
        public int DeptCode { get; set; }
        public string DeptName { get; set; }
        public int DeptShort { get; set; }
        public string DeptDesc { get; set; }
        public int DeptRoot { get; set; }
        public int BranchLevel { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string BranchLeader { get; set; }
        public Nullable<int> WXBMCode { get; set; }
        public string TXLQX { get; set; }
        public string RoleQX { get; set; }
        public string IsHasQX { get; set; }
        public string RoomCode { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
    }
}
