//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JH_Auth_WXPJ
    {
        public int ID { get; set; }
        public string TJID { get; set; }
        public string TJSecret { get; set; }
        public string Token { get; set; }
        public string EncodingAESKey { get; set; }
        public string Ticket { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string TJName { get; set; }
        public string TJStatus { get; set; }
    }
}
