//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JH_Auth_Common
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public string MenuCode { get; set; }
        public string MenuName { get; set; }
        public string Url { get; set; }
        public string Url1 { get; set; }
        public string Url2 { get; set; }
        public string ModelCode { get; set; }
        public string Remark { get; set; }
        public string Sort { get; set; }
        public Nullable<int> TopID { get; set; }
        public string Status { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
    }
}
