//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JH_Auth_WXMSG
    {
        public int ID { get; set; }
        public Nullable<int> ComId { get; set; }
        public string MsgType { get; set; }
        public string ToUserName { get; set; }
        public string FromUserName { get; set; }
        public string MediaId { get; set; }
        public string ThumbMediaId { get; set; }
        public string MsgId { get; set; }
        public Nullable<int> AgentID { get; set; }
        public string MsgContent { get; set; }
        public string PicUrl { get; set; }
        public string URL { get; set; }
        public string Format { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CRUser { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public string FileId { get; set; }
        public string ModeCode { get; set; }
        public string Tags { get; set; }
    }
}
