//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JH_Auth_Model
    {
        public int ID { get; set; }
        public string ModelName { get; set; }
        public string ModelType { get; set; }
        public string Remark1 { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string TJId { get; set; }
        public string ModelStatus { get; set; }
        public string ModePicUrl { get; set; }
        public string AppID { get; set; }
        public string ModelUrl { get; set; }
        public string IsSQ { get; set; }
        public string ModelCode { get; set; }
        public string RelTable { get; set; }
        public string AppType { get; set; }
        public string Files { get; set; }
        public Nullable<int> ComId { get; set; }
        public Nullable<int> ORDERID { get; set; }
        public Nullable<int> IsSys { get; set; }
        public string WXUrl { get; set; }
        public Nullable<int> IsKJFS { get; set; }
        public string PModelCode { get; set; }
        public string Token { get; set; }
        public string EncodingAESKey { get; set; }
    }
}
