//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JH_Auth_YYLog
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public string QYName { get; set; }
        public string CorpID { get; set; }
        public string TJID { get; set; }
        public string ModelCode { get; set; }
        public string UserName { get; set; }
        public string UserRealName { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CRUser { get; set; }
        public string Type { get; set; }
        public string Event { get; set; }
        public string EventKey { get; set; }
        public string AgentID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public string Remark { get; set; }
    }
}
