//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JH_Auth_QY_Model
    {
        public int ID { get; set; }
        public Nullable<int> ComId { get; set; }
        public Nullable<int> ModelID { get; set; }
        public string Status { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public Nullable<int> PDID { get; set; }
        public string AgentId { get; set; }
        public string QYModelCode { get; set; }
        public string ModelAdmin { get; set; }
        public Nullable<int> IsInit { get; set; }
    }
}
