//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JH_Auth_ExtendData
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public string TableName { get; set; }
        public Nullable<int> ExtendModeID { get; set; }
        public Nullable<int> DataID { get; set; }
        public string ExtendDataValue { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public Nullable<int> BranchNo { get; set; }
        public Nullable<int> PDID { get; set; }
        public string ExFiledName { get; set; }
        public string ExFiledColumn { get; set; }
        public string CRUserName { get; set; }
        public string BranchName { get; set; }
    }
}
