//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_TXL
    {
        public int ID { get; set; }
        public string LXName { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CRUser { get; set; }
        public string TagName { get; set; }
        public string UPUser { get; set; }
        public Nullable<System.DateTime> UPDDate { get; set; }
        public string LXHM { get; set; }
        public string LXMail { get; set; }
        public string LXRemark { get; set; }
        public Nullable<int> ComId { get; set; }
    }
}
