//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_TXSX
    {
        public int ID { get; set; }
        public Nullable<int> ComId { get; set; }
        public string Type { get; set; }
        public string TXUser { get; set; }
        public string TXContent { get; set; }
        public string Remark { get; set; }
        public string TXType { get; set; }
        public string Days { get; set; }
        public string Date { get; set; }
        public string Hour { get; set; }
        public string Minute { get; set; }
        public string CFType { get; set; }
        public Nullable<int> CFCount { get; set; }
        public Nullable<System.DateTime> CFJZDate { get; set; }
        public Nullable<int> ZXCount { get; set; }
        public string PCLink { get; set; }
        public string WXLink { get; set; }
        public string Status { get; set; }
        public string CRUser { get; set; }
        public string CRUserRealName { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string UpdateUser { get; set; }
        public string UpdateRealName { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int intProcessStanceid { get; set; }
        public Nullable<System.DateTime> LstSendTime { get; set; }
        public string MsgID { get; set; }
        public string APIName { get; set; }
        public string FunName { get; set; }
        public string TXMode { get; set; }
        public string ISCS { get; set; }
    }
}
