//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_XXFBType
    {
        public int ID { get; set; }
        public Nullable<int> ComId { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> PTypeID { get; set; }
        public string TypeDec { get; set; }
        public string TypeManager { get; set; }
        public string CheckUser { get; set; }
        public string IsCheck { get; set; }
        public string TypePath { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public Nullable<int> IsDel { get; set; }
        public string IsSee { get; set; }
        public string SeeUser { get; set; }
        public string ISzjfb { get; set; }
    }
}
