//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_XXFB_ITEM
    {
        public int ID { get; set; }
        public string XXTitle { get; set; }
        public string XXContent { get; set; }
        public Nullable<System.DateTime> FBTime { get; set; }
        public string remark { get; set; }
        public string remark1 { get; set; }
        public string remark2 { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CRUser { get; set; }
        public string CRUserName { get; set; }
        public string ReadUser { get; set; }
        public Nullable<int> MsgType { get; set; }
        public Nullable<int> ComId { get; set; }
        public Nullable<int> isPL { get; set; }
        public Nullable<int> XXFBId { get; set; }
        public string Files { get; set; }
        public string Author { get; set; }
        public string ImageIds { get; set; }
    }
}
