//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_XXFB
    {
        public int ID { get; set; }
        public string XXTitle { get; set; }
        public Nullable<int> isPL { get; set; }
        public Nullable<int> intProcessStanceid { get; set; }
        public Nullable<int> XXFBType { get; set; }
        public Nullable<int> MsgType { get; set; }
        public string JSUser { get; set; }
        public Nullable<int> ComId { get; set; }
        public string IsSecret { get; set; }
        public Nullable<System.DateTime> FBTime { get; set; }
        public string Files { get; set; }
        public string BZDanWei { get; set; }
        public string SHUser { get; set; }
        public Nullable<System.DateTime> SHDate { get; set; }
        public Nullable<int> SHStatus { get; set; }
        public string SHYJ { get; set; }
        public string IsSend { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CRUserName { get; set; }
        public string Remark { get; set; }
        public string SCUser { get; set; }
        public string IsSH { get; set; }
    }
}
