//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yan_WF_TI
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public string TDCODE { get; set; }
        public int PIID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string TaskUserID { get; set; }
        public string TaskUserView { get; set; }
        public string zhuandanfrom { get; set; }
        public string zhuandanto { get; set; }
        public string NextTaskInstance { get; set; }
        public string PreTaskInstance { get; set; }
        public Nullable<int> TaskState { get; set; }
        public Nullable<int> ChiTaskCount { get; set; }
        public string ChiTaskType { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string TaskName { get; set; }
        public string TaskRole { get; set; }
    }
}
