//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yan_WF_ChiTask
    {
        public string ComId { get; set; }
        public int ID { get; set; }
        public string TaskInstanceID { get; set; }
        public string TaskUser { get; set; }
        public Nullable<System.DateTime> TaskEndDate { get; set; }
        public Nullable<System.DateTime> Crdate { get; set; }
        public string CrUser { get; set; }
        public string IsHasManager { get; set; }
        public string UserView { get; set; }
        public string Remark { get; set; }
        public string isCounterSign { get; set; }
    }
}
