//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yan_WF_PD
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public string ProcessName { get; set; }
        public string RelatedTable { get; set; }
        public string Alias { get; set; }
        public string Poption { get; set; }
        public string ProcessType { get; set; }
        public string IsDefineCompleted { get; set; }
        public string IsSuspended { get; set; }
        public Nullable<int> DueDate { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CRUserName { get; set; }
        public Nullable<int> lcstatus { get; set; }
        public string isTemp { get; set; }
        public string Tempcontent { get; set; }
        public string ChaoSongUser { get; set; }
        public string ManageUser { get; set; }
        public string ManageRole { get; set; }
        public string ProcessClass { get; set; }
        public string Files { get; set; }
        public string ExportFile { get; set; }
        public string CRUser { get; set; }
        public string SQUser { get; set; }
        public string fmdata { get; set; }
        public string gltable { get; set; }
        public string gltable1 { get; set; }
        public string isgltable { get; set; }
    }
}
