//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yan_WF_TD
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public string TaskName { get; set; }
        public Nullable<int> ProcessDefinitionID { get; set; }
        public Nullable<int> Taskorder { get; set; }
        public string pretask { get; set; }
        public string NodeType { get; set; }
        public string ProcessLogic { get; set; }
        public string AssignedRole { get; set; }
        public string TaskAssInfo { get; set; }
        public string AboutAttached { get; set; }
        public string ReadableFields { get; set; }
        public string WritableFields { get; set; }
        public Nullable<int> DueDate { get; set; }
        public string AssignedUsers { get; set; }
        public string isforbid { get; set; }
        public string IsDetailUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CRUser { get; set; }
        public string isSJ { get; set; }
        public string TDCODE { get; set; }
        public string isCanEdit { get; set; }
    }
}
