//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.BusinessData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_TSSQ
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string HTNR { get; set; }
        public Nullable<int> LeiBie { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Status { get; set; }
        public string Files { get; set; }
        public Nullable<int> ComId { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string CYR { get; set; }
        public string URL { get; set; }
        public string TZR { get; set; }
        public string TZBM { get; set; }
        public string ISJH { get; set; }
        public string biaoqian { get; set; }
        public string RedUsers { get; set; }
    }
}
