//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.BusinessData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_GZGL
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public string Year { get; set; }
        public string Month { get; set; }
        public string BranchName { get; set; }
        public string UserName { get; set; }
        public string UserRealName { get; set; }
        public Nullable<decimal> JBGZ { get; set; }
        public Nullable<decimal> GWJT { get; set; }
        public Nullable<decimal> JX { get; set; }
        public Nullable<decimal> FL { get; set; }
        public Nullable<decimal> KK { get; set; }
        public Nullable<decimal> YFGZ { get; set; }
        public Nullable<decimal> SFGZ { get; set; }
        public Nullable<decimal> GRJN { get; set; }
        public Nullable<decimal> GSJN { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Status { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
    }
}
