//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QJY.BusinessData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZHL_GZGL_JCSZ
    {
        public Nullable<int> ComId { get; set; }
        public int ID { get; set; }
        public string UserName { get; set; }
        public Nullable<decimal> JBGZ { get; set; }
        public Nullable<decimal> GWJT { get; set; }
        public Nullable<int> IsSB { get; set; }
        public Nullable<int> IsGJJ { get; set; }
        public string Files { get; set; }
        public string Remark { get; set; }
        public string CRUser { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
    }
}
